version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: ${NODE_ENV}
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DIALECT: ${POSTGRES_DIALECT}
      POSTGRES_DB: ${POSTGRES_DB}
      NODE_ENV: ${NODE_ENV}
  postgres:
    image: postgres:14.1-alpine
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DIALECT: ${POSTGRES_DIALECT}
      POSTGRES_DB: ${POSTGRES_DB}
      NODE_ENV: ${NODE_ENV}
    ports:
      - '5432:5432'
    volumes:
      - cryptomarketcap:/var/lib/postgresql/data
volumes:
  cryptomarketcap:

