version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
    - .env.local
    command: npm run start:dev
    ports:
      - '3000:3000'
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DIALECT: ${POSTGRES_DIALECT}
      POSTGRES_NAME: ${POSTGRES_NAME}
      NODE_ENV: ${NODE_ENV}
    ports:
      - '5432:5432'
    volumes:
      - cryptomarketcap:/var/lib/postgresql/data
      - ./scripts/init.sh:/docker-entrypoint-initdb.d/init.sh
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
volumes:
  cryptomarketcap:
    driver: local
